CREATE TABLE `client` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` varchar(64) NOT NULL COMMENT '姓名',
  `gender` tinyint(4) DEFAULT NULL COMMENT '性别 1男 2女',
  `phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `birthday` varchar(20) DEFAULT NULL COMMENT '出生年月 YYYY-MM-DD',
  `zodiac` varchar(10) DEFAULT NULL COMMENT '属相',
  `height` int(11) DEFAULT NULL COMMENT '身高cm',
  `weight` int(11) DEFAULT NULL COMMENT '体重kg',
  `education` tinyint(4) DEFAULT NULL COMMENT '学历',
  `marital_status` tinyint(4) DEFAULT NULL COMMENT '婚姻状况',
  `address` varchar(255) DEFAULT NULL COMMENT '家庭住址',
  `family_description` text COMMENT '家庭成员描述',
  `income` int(11) DEFAULT NULL COMMENT '月收入',
  `profession` varchar(128) DEFAULT NULL COMMENT '具体工作',
  `house_status` tinyint(4) DEFAULT NULL COMMENT '房产情况',
  `car_status` tinyint(4) DEFAULT NULL COMMENT '车辆情况',
  `partner_requirements` text COMMENT '对另一半要求',
  `remark` text COMMENT '红娘备注',
  `photos` text COMMENT '照片URL列表(JSON)',
  `created_at` datetime(3) DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime(3) DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_phone` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户档案表';
