// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/iWuxc/go-wit/app"
	"omiai-server/internal/conf"
	"omiai-server/internal/controller/ai"
	"omiai-server/internal/controller/auth"
	banner2 "omiai-server/internal/controller/banner"
	"omiai-server/internal/controller/china_region"
	"omiai-server/internal/controller/client"
	"omiai-server/internal/controller/common"
	"omiai-server/internal/controller/dashboard"
	"omiai-server/internal/controller/match"
	"omiai-server/internal/controller/reminder"
	"omiai-server/internal/controller/template"
	"omiai-server/internal/cron"
	"omiai-server/internal/data"
	"omiai-server/internal/data/omiai"
	"omiai-server/internal/middleware"
	"omiai-server/internal/queues"
	"omiai-server/internal/server"
	"omiai-server/internal/service/banner"
	"omiai-server/internal/service/chat_parser"
)

// Injectors from wire.go:

func initApp(ctx context.Context) (*app.App, func(), error) {
	db, cleanup, err := data.NewDB()
	if err != nil {
		return nil, nil, err
	}
	v := middleware.NewMiddleWares(db)
	engine := server.NewGinEngine(v)
	redis, err := server.NewRedisX()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	clientInterface := omiai.NewClientRepo(db)
	controller := ai.NewController(db, clientInterface)
	userInterface := omiai.NewUserRepo(db)
	authController := auth.NewController(db, userInterface)
	bannerInterface := omiai.NewBannerRepo(db)
	service := banner.NewService(redis)
	bannerController := banner2.NewController(db, bannerInterface, service)
	china_regionController := china_region.NewController(db)
	chatParser := chat_parser.NewChatParser()
	clientController := client.NewController(db, clientInterface, chatParser)
	config := conf.GetConfig()
	driver, err := data.NewStorage(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	commonController := common.NewController(driver)
	templateRepo := omiai.NewTemplateRepo(db)
	templateController := template.NewController(templateRepo)
	reminderInterface := omiai.NewReminderRepo(db)
	reminderController := reminder.NewController(db, reminderInterface)
	matchInterface := omiai.NewMatchRepo(db)
	dashboardController := dashboard.NewController(clientInterface, matchInterface, reminderInterface)
	matchController := match.NewController(db, matchInterface, clientInterface, userInterface)
	router := &server.Router{
		Engine:                engine,
		DB:                    db,
		Redis:                 redis,
		AIController:          controller,
		AuthController:        authController,
		BannerController:      bannerController,
		ChinaRegionController: china_regionController,
		ClientController:      clientController,
		CommonController:      commonController,
		TemplateController:    templateController,
		ReminderController:    reminderController,
		DashboardController:   dashboardController,
		MatchController:       matchController,
	}
	v2 := server.NewHTTPServer(router)
	userProductFinalizer := cron.NewUserProductFinalizer(db)
	candidatePreFilterService := cron.NewCandidatePreFilterService(db)
	reminderService := cron.NewReminderService(db, reminderInterface, clientInterface, matchInterface)
	reminderCronJob := cron.NewReminderCronJob(reminderService)
	initCron := &cron.InitCron{
		UserProductFinalizer:      userProductFinalizer,
		CandidatePreFilterService: candidatePreFilterService,
		ReminderCronJob:           reminderCronJob,
	}
	dcron, err := cron.NewCron(initCron)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	outfitRatingQueue := queues.NewOutfitRatingQueue(db, redis)
	initQueue := &queues.InitQueue{
		OutfitRatingQueue: outfitRatingQueue,
	}
	serverServer := queues.NewQueue(initQueue)
	appApp, cleanup2, err := newApp(ctx, v2, dcron, serverServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return appApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
