// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/iWuxc/go-wit/app"
	"omiai-server/internal/conf"
	"omiai-server/internal/controller/auth"
	banner2 "omiai-server/internal/controller/banner"
	"omiai-server/internal/controller/client"
	"omiai-server/internal/controller/common"
	"omiai-server/internal/controller/match"
	"omiai-server/internal/cron"
	"omiai-server/internal/data"
	"omiai-server/internal/data/omiai"
	"omiai-server/internal/middleware"
	"omiai-server/internal/queues"
	"omiai-server/internal/server"
	"omiai-server/internal/service/banner"
	"omiai-server/internal/service/chat_parser"
)

// Injectors from wire.go:

func initApp(ctx context.Context) (*app.App, func(), error) {
	db, cleanup, err := data.NewDB()
	if err != nil {
		return nil, nil, err
	}
	v := middleware.NewMiddleWares(db)
	engine := server.NewGinEngine(v)
	redis, err := server.NewRedisX()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userInterface := omiai.NewUserRepo(db)
	controller := auth.NewController(db, userInterface)
	bannerInterface := omiai.NewBannerRepo(db)
	service := banner.NewService(redis)
	bannerController := banner2.NewController(db, bannerInterface, service)
	clientInterface := omiai.NewClientRepo(db)
	chatParser := chat_parser.NewChatParser()
	clientController := client.NewController(db, clientInterface, chatParser)
	config := conf.GetConfig()
	driver, err := data.NewStorage(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	commonController := common.NewController(driver)
	matchInterface := omiai.NewMatchRepo(db)
	matchController := match.NewController(db, matchInterface, clientInterface)
	router := &server.Router{
		Engine:           engine,
		DB:               db,
		Redis:            redis,
		AuthController:   controller,
		BannerController: bannerController,
		ClientController: clientController,
		CommonController: commonController,
		MatchController:  matchController,
	}
	v2 := server.NewHTTPServer(router)
	userProductFinalizer := cron.NewUserProductFinalizer(db)
	initCron := &cron.InitCron{
		UserProductFinalizer: userProductFinalizer,
	}
	dcron, err := cron.NewCron(initCron)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	outfitRatingQueue := queues.NewOutfitRatingQueue(db, redis)
	initQueue := &queues.InitQueue{
		OutfitRatingQueue: outfitRatingQueue,
	}
	serverServer := queues.NewQueue(initQueue)
	appApp, cleanup2, err := newApp(ctx, v2, dcron, serverServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return appApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
