// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"omiai-server/cmd/script/command"
	"omiai-server/internal/data"
)

// Injectors from wire.go:

func initApp(ctx context.Context) (*InitCmd, func(), error) {
	db, cleanup, err := data.NewDB()
	if err != nil {
		return nil, nil, err
	}
	script := command.NewScript(db)
	initCmd := &InitCmd{
		Command: script,
	}
	return initCmd, func() {
		cleanup()
	}, nil
}
